#Server configuration
server:
  port: 8080

# Database configuration
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DB_HOST}/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  jpa:
    properties:
      hibernate:
        format_sql: true

    hibernate:
      ddl-auto: create

jwt:
  secret-key: ${jwt_secret_key}

  access:
    expiration: 345600 # 4days
    header: Authorization

  refresh:
    expiration: 1209600 # 14days
    header: Authorization-refresh